---
project:
  name: "name_of_the_project"
  directory: "directory_of_the_project"

base_urls:
- "link_to_crawl1"
- "link_to_crawl1"

num_worker_threads: 4

request:
  timeout: 60

proxies:
  http: "socks5h://127.0.0.1:9050"
  https: "socks5h://127.0.0.1:9050"
