project_directory: '/home/user/Desktop/dwc'
project_name: 'hidden_wiki'

results_data_name: 'crawling_results'

base_urls:
  - 'https://thehiddenwiki.org/'

urls_to_crawl_file: 'links_to_crawl.txt'
crawled_urls_file: 'crawled_links.txt'

num_worker_threads: 1

proxies:
  http: 'socks5h://127.0.0.1:9050'
  https: 'socks5h://127.0.0.1:9050'
